name: hourly-xdu-planet

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - web


jobs:
  run-xdu-planet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run xdu-planet
      run: bash xdu-planet --update-db
