name: hourly-xdu-planet

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - web
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        path: ./
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: build
      run: go build
    - name: run
      run: ./xdu-planet -fetch
