name: hourly-xdu-planet

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - web
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        path: ./
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: web
        path: ./public
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 17
    - name: Build
      run: cd frontend && npm install pnpm -g && pnpm install && pnpm run build --outDir ../public && cd ..
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: build
      run: go mod tidy && go build -o ./public/xdu-planet && cd public && ./xdu-planet -fetch
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        REPOSITORY_NAME: xeonds/xdu-planet
        BRANCH: web
        FOLDER: public